// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package demo

import (
	"database/sql"
)

type A struct {
	AID   sql.NullString
	BIDFk sql.NullString
}

type B struct {
	BID sql.NullString
}
